name = "demo"
main = "src/worker.ts"
compatibility_date = "2023-05-28"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "auth"
database_id = "21200feb-9032-4c7a-8364-4a080dbbdf02"